version: '3.9'

services:
  db:
    image: postgres:14-alpine
    container_name: daytoday_db
    environment:
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
      - POSTGRES_DB=daytoday_db
    ports:
      - 5432:5432
