spring:
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/daytoday_db
    username: db
    password: db
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
